### ISSUE TITLE
Bug Final Fantasy III save/load and name entry screen

### ISSUE THREAD

**Issue by CharlesBukowski** [libretro/snes9x-next#46]
There is a graphical glitch on the save/load screen and name entry screen when playing FFIII. Instead of solid blue, the windows have two shades of blue.

**Comment by CharlesBukowski** [comment]
Actually, I'm noticing this issue with many of the in-game menus, not just the load screen and name entry screen.

**Comment by twinaphex** [comment]
Final Fantasy III has several in-game speedhacks enabled in SNES9x Next which were intended to prevent certain performance-crippling dips on the Wii from occurring.

I'll make this an optional core option, that should get rid of the inaccuracies. An alternative is just using the libretro snes9x vanilla core for now.

**Comment by CharlesBukowski** [comment]
Thanks! Will disabling the speed hacks cause performance problems on the raspberry pi?

**Comment by twinaphex** [comment]
Yes it would negatively affect performance.

**Comment by CharlesBukowski** [comment]
Is there no way to address the inaccuracies without it affecting performance? I don't remember this being a problem with regular snes9x. I would use regular snes9x but I don't think that runs on the pi.

**Comment by twinaphex** [comment]
No, it's not an exact science as you're finding out right now.

**Comment by CharlesBukowski** [comment]
Alright, thanks for clearing that up- I guess it's pretty amazing that this stuff runs on the pi at all.

**Comment by CharlesBukowski** [comment]
Would it be possible to address the issue with a game-specific hack of some sort? Just wondering because it's a AAA title and extremely popular.

**Comment by CharlesBukowski** [comment]
I found that Catsfc will run FFIII without issue- well, maybe an occasional sound glitch, but nothing worse than what you would get in a typical Square Enix port :-P

So, Catsfc is doing something right. Just thought I'd pass that along.
