### ISSUE TITLE
Exit emulator setting not being honored

### ISSUE THREAD

**Issue by ElementalWarrior** [libretro/snes9x-next#47]
I have the input exit emulator setting set in the retroarch.cfg config file. However when I hit esc in the emulator nothing happens?

Thoughts? Ideas?

**Comment by twinaphex** [comment]
This has nothing to do with the SNES9x Next core. It is likely you just configured RetroArch wrong.

**Comment by ElementalWarrior** [comment]
I'm running retropie and have other snes emulators running in retroarch and
they exit fine...

**Comment by twinaphex** [comment]
I have nothing to do with RetroPIe. It's likely their fault.

**Comment by ElementalWarrior** [comment]
They just reuse the same retroarch.cfg for the different config files. I
built snes9x-next from git and just added it to the script that will start
the emulator for you.

**Comment by twinaphex** [comment]
Like I said, I know nothing about RetroPie and am not involved in its development. I can assure you this is not a RetroArch bug. Whatever issue you may have, it is not related to the SNES9x libretro core, or RetroArch.
