### ISSUE TITLE
Slowdown in latest version

### ISSUE THREAD

**Issue by TheBeverage** [libretro/snes9x-next#49]
Hi, using the version bundled with Retroarch 1.2.1 and the latest nightly for Wii, there is a significant amount of slowdown in certain games as opposed to 1.0.0.2, most notably the intro to Yoshi's Island runs at around 50fps where it used to be at 59-60.

**Comment by askotx** [comment]
+1, tested in Star Fox, if you leave FX overclock disabled, it runs to 60 FPS, but kinda slow but if you set it to 40, etc, fps will go slowdown more

**Comment by twinaphex** [comment]
You guys are barking up the wrong tree, there were no performance regressions in SNES9x Next core but in RetroArch the frontend itself. I don't know yet what is causing the performance difference in 1.0.0.2 vs. 1.2.x, it should be possible to get that performance back over time but do note that Wii right now is not the main priority of RetroArch at this point.

**Comment by askotx** [comment]
OK, if it's not a performance regression, then what is it? I've compiled lastest of snes9x-next (ba8a662a36601a19e07fe46c552a96572cba19c8) source with retroarch v1.0.0.2 with (320b9b8745d69f149e25e4c049828ed7447a960e) and yes SFX emulation it's slow, have you tested?

**Comment by twinaphex** [comment]
Come up with a PR that brings the performance back then.

**Comment by askotx** [comment]
ok, I'll send a PR, but it was a long time ago, let me test more to give you an exact commit, but it was between e3ac4fd502dbda20cc4bc0f4c92fa1cd09739ac2 and 8e21037456936a94b4f1709a9ad0f04e889a1ce0, something about APU, I'm no expert, I just compile it for my kids, they like playing retroarch on wii

**Comment by askotx** [comment]
I've tested all this commits: 

e3ac4fd502dbda20cc4bc0f4c92fa1cd09739ac2 (APU changed)
e51191f32391586468e6fbb5aea8ed7581a7c927 (MSB)
ba8a662a36601a19e07fe46c552a96572cba19c8 (master 4 days ago)
8e21037456936a94b4f1709a9ad0f04e889a1ce0 (before APU changes)

All of them get SFX emulation slowndown, to solve it just set Sample Rate to 32000 and FPS will go to 59~60, so @twinaphex you can close this and sorry for my mistake.

**Comment by TheBeverage** [comment]
"Sample rate"? Where would that option be?

**Comment by fr500** [comment]
under audio settings

**Comment by askotx** [comment]
You must edit manually your retroarch.cfg file and search for audio_out_rate = "48000", just change it to 32000

**Comment by TheBeverage** [comment]
Took me a while to have some free time, but the audio fix works! Thanks a lot.
