### ISSUE TITLE
Wrong colors on Android

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/snes9x-next#54]
Wrong colors on Android, nightly from 2015-08-20:

![screenshot_2015-08-20-01-45-03](https://cloud.githubusercontent.com/assets/5431285/9375973/6cd460b2-46dd-11e5-8f00-08c92356c999.png)

**Comment by twinaphex** [comment]
This commit should hopefully fix it on the next nightly -

https://github.com/libretro/snes9x-next/commit/bf3bd3a11582f297bda86a74414e3e3969175213

**Comment by sergiobenrocha2** [comment]
Downloaded the core again, same issue.

**Comment by sergiobenrocha2** [comment]
It's working, thanks!
