### ISSUE TITLE
Super Bomberman 5 : joypad 2 controls players 2,3,4,5

### ISSUE THREAD

**Issue by Kivutar** [libretro/snes9x-next#63]

**Comment by DarkHanswurst** [comment]
I have found the issue.
Super Bomberman 5 is missing in the list of multitap supporting games and therefore `Settings.CurrentROMisMultitapCompatible` is never set to true.

Adding the line `MATCH_ID("A5SJ") ||				/* Super Bomberman 5*/` (after line 3146 for aexample) in the `memmap.c` file will fix this.
